server:
  port: 5000

spring:
  datasource:
    password: IKRAM.hiba2004
    url: jdbc:mysql://localhost:3306/orwan
    username: root
  jpa:
    hibernate:
      ddl-auto : create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show_sql: true


